"""Add parent dashboard models

Revision ID: 0f726d29de4f
Revises: 5e842217fdf9
Create Date: 2024-11-20 19:20:49.747109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f726d29de4f'
down_revision = '5e842217fdf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sharing_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wishlist_id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wishlist_id'], ['wishlists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('wishlist_id', sa.Integer(), nullable=True),
    sa.Column('sharing_request_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sharing_request_id'], ['sharing_requests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['wishlist_id'], ['wishlists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('date_of_birth', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('requires_parent_approval', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('can_manage_account', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('sharing_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('notifications_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_activity', sa.DateTime(), nullable=True))
        batch_op.drop_column('reset_token')
        batch_op.drop_column('last_login')
        batch_op.drop_column('password_hash')
        batch_op.drop_column('is_child')
        batch_op.drop_column('is_verified')
        batch_op.drop_column('reset_token_expiry')
        batch_op.drop_column('google_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('reset_token_expiry', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('is_verified', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('is_child', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('last_login', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('reset_token', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('last_activity')
        batch_op.drop_column('notifications_enabled')
        batch_op.drop_column('sharing_enabled')
        batch_op.drop_column('can_manage_account')
        batch_op.drop_column('requires_parent_approval')
        batch_op.drop_column('date_of_birth')
        batch_op.drop_column('password')

    op.drop_table('notifications')
    op.drop_table('sharing_requests')
    # ### end Alembic commands ###
